### ISSUE TITLE
random crash when first installing the mod to x86 program folder of steam folder

### ISSUE THREAD

**Issue by bloodyframe2018** [Mee12345/GMod-Procedural-Terrain#1]
i just desited to play with the terrain but was greeted imidgetly with a crash.

**Comment by Fasteroid** [comment]
get a better computer

**Comment by bloodyframe2018** [comment]
> get a better computer

explain why i should. when i have a rtx 2060 msi laptop

**Comment by Derpius** [comment]
Your first mistake was using code from Mee
Your second mistake was using his terrain code that has always been crashy since he wrote it in Starfall

**Comment by bloodyframe2018** [comment]
how do you know? derplus?

**Comment by Derpius** [comment]
![image](https://user-images.githubusercontent.com/49565664/170612861-ea65cbfb-6133-42af-a4ca-d33bdd6ec908.png)
![image](https://user-images.githubusercontent.com/49565664/170613143-30e49462-b133-4031-ac2b-e97e6470c0e3.png)


He also completely crashed "his" server with it

**Comment by meetric1** [comment]
The 32 bit branch has a memory leak with reguard to generating physics objects on the client

switching to 64 bit will likely solve all your problems, other than that I havent experienced any crashing

unfortunately I am unsure how to fix this issue, as it exists pretty much everywhere including in starfall custom props

Also dont worry, everything about the starfall implementation was scrapped (except for some file and variable names)

**Comment by bloodyframe2018** [comment]
> The 32 bit branch has a memory leak with reguard to generating physics objects on the client
> 
> switching to 64 bit will likely solve all your problems, other than that I havent experienced any crashing
> 
> unfortunately I am unsure how to fix this issue, as it exists pretty much everywhere including in starfall custom props
> 
> Also dont worry, everything about the starfall implementation was scrapped (except for some file and variable names)

could you make the mod not for hl:2 epsiode 2. i don't have it

**Comment by meetric1** [comment]
this *should* be fixed, I tested on 32 bit branch several times and had no crash. I think the tree collisions were causing issues.
