### ISSUE TITLE
Missing menu items, causing nil error in the code: terrain_menu.lua

### ISSUE THREAD

**Issue by smmarkvard** [Mee12345/GMod-Procedural-Terrain#3]

**Comment by meetric1** [comment]
not very useful information, please give the exact error message and more info on what you did to cause the error

**Comment by smmarkvard** [comment]
oh yeah sry. I didn't have time to write a full bug report and forgot
all about it. Hopefully, the bugs is already gone

Den man. 4. jul. 2022 kl. 02.28 skrev Mee12345 ***@***.***>:
